# This is a config for E2B sandbox template.
# You can use template ID (poixc5410padrckjk7vp) or template name (vibe-nextjs-thestu) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-thestu") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-thestu") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-thestu')

team_id = "176f4b3c-c71f-4ca1-80e8-f694941fc391"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-thestu"
template_id = "poixc5410padrckjk7vp"
